import type { AutomationIpcRequest, AutomationIpcResponse, AgentSummary, AgentFile, AgentWorkspaceEntry, CronJob, CronRun } from "@uclaw/shared";
import { Bot, CalendarClock, FileText, LoaderCircle, Play, Plus, RefreshCw, Save, Trash2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

type Invoke = (request: AutomationIpcRequest) => Promise<AutomationIpcResponse>;
export interface AutomationManagerProps { invoke?: Invoke; }

function list(value: unknown, key: string): unknown[] { return value && typeof value === "object" && Array.isArray((value as Record<string, unknown>)[key]) ? (value as Record<string, unknown>)[key] as unknown[] : []; }

export function AutomationManager({ invoke: suppliedInvoke }: AutomationManagerProps) {
  const sequence = useRef(0);
  const invoke = suppliedInvoke ?? (window as unknown as { uclaw?: { automation?: { invoke: Invoke } } }).uclaw?.automation?.invoke;
  const [tab, setTab] = useState<"agents" | "cron">("agents");
  const [agents, setAgents] = useState<AgentSummary[]>([]); const [jobs, setJobs] = useState<CronJob[]>([]);
  const [selectedAgent, setSelectedAgent] = useState<string>(); const [selectedCron, setSelectedCron] = useState<string>(); const [files, setFiles] = useState<AgentFile[]>([]); const [workspace, setWorkspace] = useState<AgentWorkspaceEntry[]>([]);
  const [file, setFile] = useState<AgentFile>(); const [workspaceFile, setWorkspaceFile] = useState<AgentWorkspaceEntry>(); const [runs, setRuns] = useState<CronRun[]>([]); const [cronDetail, setCronDetail] = useState<CronJob>();
  const [status, setStatus] = useState<{ enabled?: boolean; jobCount?: number; nextWakeAtMs?: number }>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const [agentName, setAgentName] = useState("New Agent"); const [agentWorkspace, setAgentWorkspace] = useState(""); const [agentModel, setAgentModel] = useState(""); const [workspacePath, setWorkspacePath] = useState(""); const [workspaceParent, setWorkspaceParent] = useState<string>(); const [cronName, setCronName] = useState("New schedule");
  const [cronExpression, setCronExpression] = useState("0 9 * * *"); const [cronMessage, setCronMessage] = useState("Run scheduled task"); const [cronEnabled, setCronEnabled] = useState(true);
  const call = useCallback(async (method: AutomationIpcRequest["method"], params: Record<string, unknown>) => {
    if (!invoke) throw new Error("Agent/Cron RPC 未配置");
    const response = await invoke({ method, requestId: `automation-${++sequence.current}`, params } as AutomationIpcRequest);
    if (!response.ok) throw new Error(`${response.error?.code ?? "UNKNOWN"}: ${response.error?.message ?? "操作失败"}`);
    return response.result;
  }, [invoke]);
  const refreshAgents = useCallback(async () => setAgents(list(await call("agents.list", {}), "agents") as AgentSummary[]), [call]);
  const refreshCron = useCallback(async () => { const [jobValue, statusValue] = await Promise.all([call("cron.list", {}), call("cron.status", {})]); setJobs(list(jobValue, "jobs") as CronJob[]); setStatus(statusValue as { enabled?: boolean; jobCount?: number; nextWakeAtMs?: number }); }, [call]);
  const run = async (fn: () => Promise<void>) => { setBusy(true); setError(undefined); try { await fn(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  useEffect(() => { if (!invoke) return; void run(refreshAgents); }, [invoke, refreshAgents]);
  const loadWorkspace = async (agentId: string, path?: string) => { const value = await call("agents.workspace.list", { agentId, ...(path ? { path } : {}) }); const result = value as { path?: string; parentPath?: string; entries?: AgentWorkspaceEntry[] }; setWorkspace(result.entries ?? []); setWorkspacePath(result.path ?? ""); setWorkspaceParent(result.parentPath); setWorkspaceFile(undefined); };
  const selectAgent = (agent: AgentSummary) => run(async () => {
    const agentId = agent.id; setAgentWorkspace(agent.workspace ?? ""); setAgentModel(agent.model ?? "");
    setSelectedAgent(agentId); const [identity, fileValue, workspaceValue] = await Promise.all([call("agent.identity.get", { agentId }), call("agents.files.list", { agentId }), call("agents.workspace.list", { agentId })]);
    const identityName = identity && typeof identity === "object" ? (identity as { name?: string }).name : undefined; if (identityName) setAgentName(identityName);
    const nextFiles = list(fileValue, "files") as AgentFile[]; const workspaceResult = workspaceValue as { path?: string; parentPath?: string; entries?: AgentWorkspaceEntry[] }; const nextWorkspace = workspaceResult.entries ?? []; setFiles(nextFiles); setWorkspace(nextWorkspace); setWorkspacePath(workspaceResult.path ?? ""); setWorkspaceParent(workspaceResult.parentPath);
    if (nextFiles[0]) { const value = await call("agents.files.get", { agentId, path: nextFiles[0].name }); setFile((value as { file?: AgentFile }).file); }
  });
  if (!invoke) return <div className="empty-panel"><CalendarClock /><strong>Agent/Cron RPC 未配置</strong></div>;
  return <section className="automation-manager" aria-label="Agent 与定时任务" aria-busy={busy}>
    <header className="data-toolbar"><strong>Agent 与定时任务</strong><button type="button" aria-label="刷新 Agent/Cron" disabled={busy} onClick={() => void run(tab === "agents" ? refreshAgents : refreshCron)}><RefreshCw /></button>{busy ? <LoaderCircle className="spin" /> : null}</header>
    <div role="tablist" className="settings-tabs"><button role="tab" aria-selected={tab === "agents"} onClick={() => setTab("agents")}><Bot />Agent</button><button role="tab" aria-selected={tab === "cron"} onClick={() => { setTab("cron"); void run(refreshCron); }}><CalendarClock />定时任务</button></div>
    {error ? <div role="alert" className="data-state"><strong>操作失败</strong><small>{error}</small></div> : null}
    {tab === "agents" ? <div className="automation-grid">
      <section><div className="data-toolbar"><input aria-label="Agent 名称" value={agentName} onChange={(e) => setAgentName(e.target.value)} /><input aria-label="Agent workspace" value={agentWorkspace} onChange={(e) => setAgentWorkspace(e.target.value)} /><input aria-label="Agent 模型" value={agentModel} onChange={(e) => setAgentModel(e.target.value)} /><button aria-label="创建 Agent" disabled={busy || !agentName.trim() || !agentWorkspace.trim()} onClick={() => void run(async () => { const value = await call("agents.create", { name: agentName.trim(), workspace: agentWorkspace.trim(), ...(agentModel.trim() ? { model: agentModel.trim() } : {}) }); setAgents(list(value, "agents") as AgentSummary[]); })}><Plus /></button></div>
        {agents.map((agent) => <article key={agent.id}><button aria-label={`查看 Agent ${agent.id}`} onClick={() => void selectAgent(agent)}><Bot />{agent.name ?? agent.id}</button><button aria-label={`编辑 Agent ${agent.id}`} disabled={busy || selectedAgent !== agent.id || !agentWorkspace.trim()} onClick={() => void run(async () => { const value = await call("agents.update", { agentId: agent.id, name: agentName.trim() || agent.name || agent.id, workspace: agentWorkspace.trim(), ...(agentModel.trim() ? { model: agentModel.trim() } : {}) }); setAgents(list(value, "agents") as AgentSummary[]); })}><Save /></button><button aria-label={`删除 Agent ${agent.id}`} disabled={busy} onClick={() => { if (window.confirm(`删除 Agent ${agent.name ?? agent.id}？工作区文件会保留。`)) void run(async () => { const value = await call("agents.delete", { agentId: agent.id, deleteFiles: false }); setAgents(list(value, "agents") as AgentSummary[]); }); }}><Trash2 /></button></article>)}</section>
      <section><strong>Agent 文件</strong>{files.map((entry) => <button key={entry.path} onClick={() => selectedAgent && void run(async () => { const value = await call("agents.files.get", { agentId: selectedAgent, path: entry.name }); setFile((value as { file?: AgentFile }).file); })}><FileText />{entry.name}</button>)}{file ? <><textarea aria-label="Agent 文件内容" value={file.content ?? ""} onChange={(e) => setFile({ ...file, content: e.target.value })} /><button aria-label="保存 Agent 文件" disabled={busy || !selectedAgent} onClick={() => selectedAgent && void run(async () => { const value = await call("agents.files.set", { agentId: selectedAgent, path: file.name, content: file.content ?? "" }); setFile((value as { file?: AgentFile }).file); })}><Save />保存</button></> : null}</section>
      <section><strong>Workspace · {workspacePath || "/"}</strong>{workspaceParent !== undefined ? <button aria-label="返回上级目录" onClick={() => selectedAgent && void run(() => loadWorkspace(selectedAgent, workspaceParent || undefined))}>返回上级</button> : null}{workspace.map((entry) => <button key={entry.path} onClick={() => selectedAgent && void run(async () => { if (entry.kind === "directory") return loadWorkspace(selectedAgent, entry.path); const value = await call("agents.workspace.get", { agentId: selectedAgent, path: entry.path }); setWorkspaceFile((value as { entry?: AgentWorkspaceEntry }).entry); })}>{entry.name}</button>)}{workspaceFile?.content ? <pre>{workspaceFile.content}</pre> : null}</section>
    </div> : <div className="automation-grid"><section><div className="data-toolbar"><input aria-label="定时任务名称" value={cronName} onChange={(e) => setCronName(e.target.value)} /><input aria-label="Cron 表达式" value={cronExpression} onChange={(e) => setCronExpression(e.target.value)} /><input aria-label="定时任务消息" value={cronMessage} onChange={(e) => setCronMessage(e.target.value)} /><label><input type="checkbox" aria-label="启用定时任务" checked={cronEnabled} onChange={(e) => setCronEnabled(e.target.checked)} />启用</label><button aria-label="新增定时任务" disabled={busy} onClick={() => void run(async () => { const value = await call("cron.add", { name: cronName, enabled: cronEnabled, schedule: { kind: "cron", expression: cronExpression }, payload: { kind: "agentTurn", message: cronMessage } }); setJobs(list(value, "jobs") as CronJob[]); })}><Plus /></button></div>
      {status ? <small role="status">Scheduler {status.enabled ? "启用" : "停用"} · {status.jobCount ?? jobs.length} 个任务</small> : null}{jobs.map((job) => <article key={job.id}><button aria-label={`查看定时任务 ${job.id}`} onClick={() => void run(async () => { const value = await call("cron.get", { jobId: job.id }); const detail = (value as { job?: CronJob }).job; setCronDetail(detail); setSelectedCron(detail?.schedule.kind === "cron" && detail.payload.kind === "agentTurn" ? detail.id : undefined); if (detail) { setCronName(detail.name ?? detail.displayName ?? detail.id); if (detail.schedule.kind === "cron") setCronExpression(detail.schedule.expression); setCronMessage(detail.payload.message ?? ""); setCronEnabled(detail.enabled); } })}>{job.name ?? job.displayName ?? job.id}</button><button aria-label={`编辑定时任务 ${job.id}`} disabled={busy || selectedCron !== job.id} onClick={() => void run(async () => { const value = await call("cron.update", { jobId: job.id, name: cronName, enabled: cronEnabled, schedule: { kind: "cron", expression: cronExpression }, payload: { kind: "agentTurn", message: cronMessage } }); setJobs(list(value, "jobs") as CronJob[]); })}><Save /></button><button aria-label={`删除定时任务 ${job.id}`} onClick={() => { if (window.confirm(`删除定时任务 ${job.name ?? job.id}？`)) void run(async () => { const value = await call("cron.remove", { jobId: job.id }); setJobs(list(value, "jobs") as CronJob[]); }); }}><Trash2 /></button><button aria-label={`立即运行 ${job.id}`} onClick={() => void run(async () => { await call("cron.run", { jobId: job.id }); const value = await call("cron.runs", { jobId: job.id }); setRuns(list(value, "runs") as CronRun[]); })}><Play /></button><button aria-label={`查看运行历史 ${job.id}`} onClick={() => void run(async () => setRuns(list(await call("cron.runs", { jobId: job.id }), "runs") as CronRun[]))}>历史</button></article>)}</section><section aria-label="定时任务详情"><strong>任务详情</strong>{cronDetail ? <p>{cronDetail.name ?? cronDetail.displayName ?? cronDetail.id} · {cronDetail.enabled ? "启用" : "停用"}{cronDetail.schedule.kind !== "cron" || cronDetail.payload.kind !== "agentTurn" ? " · 此任务类型只读" : ""}</p> : null}</section><section aria-label="运行历史"><strong>运行历史</strong>{runs.map((item, index) => <p key={item.id ?? `${item.jobId}-${index}`}>{item.jobId} · {item.status}</p>)}</section></div>}
  </section>;
}
