import { z } from "zod";
import { UClawErrorSchema } from "@uclaw/shared";
import type { SystemPushSubscriptionAuthority, SystemTalkSessionAuthority, SystemVoiceAudioOutput, SystemVoicePermissionReader, SystemVoicePermissions, SystemVoiceService } from "@uclaw/shared/dist/system-voice.js";

export interface OpenClawSystemVoiceOptions { request(method: string, params: unknown, schema: z.ZodType, signal?: AbortSignal): Promise<unknown>; requireMethod(method: string): void; permissions: SystemVoicePermissionReader; pushSubscription?: SystemPushSubscriptionAuthority; audioOutput?: SystemVoiceAudioOutput; talkSessions?: SystemTalkSessionAuthority; waitForTalkRun?(runId: string): Promise<unknown>; abortTalkRun?(sessionKey: string, runId: string): Promise<void>; }
const Any = z.unknown();
const fields: Record<string, ReadonlySet<string>> = {
  "talk.session.create": new Set(["sessionId", "sessionKey", "mode", "transport", "brain", "provider", "status"]), "talk.session.close": new Set(["sessionId", "closed", "status"]), "talk.client.create": new Set(["sessionId", "sessionKey", "mode", "transport", "brain", "provider", "model", "voice", "status", "expiresAt"]), "talk.client.steer": new Set(["ok", "mode", "sessionKey", "sessionId", "active", "queued", "aborted", "target", "reason", "message", "speak", "show", "suppress"]),
  "tts.status": new Set(["enabled", "auto", "provider", "persona", "fallbackProvider", "fallbackProviders", "providerStates", "id", "label", "configured"]), "tts.providers": new Set(["providers", "active", "id", "name", "configured", "models", "voices"]), "tts.setProvider": new Set(["provider"]), "tts.personas": new Set(["active", "personas", "id", "label", "description", "provider", "fallbackPolicy", "providers"]), "tts.setPersona": new Set(["persona"]), "tts.speak": new Set(["provider", "outputFormat", "mimeType", "fileExtension"]),
  "voicewake.get": new Set(["triggers"]), "voicewake.set": new Set(["triggers"]), "voicewake.routing.get": new Set(["config", "version", "defaultTarget", "routes", "mode", "agentId", "sessionKey", "trigger", "target", "updatedAtMs"]), "voicewake.routing.set": new Set(["config", "version", "defaultTarget", "routes", "mode", "agentId", "sessionKey", "trigger", "target", "updatedAtMs"]),
  "push.web.vapidPublicKey": new Set([]), "push.web.subscribe": new Set(["subscriptionId"]), "push.web.unsubscribe": new Set(["removed"]), "push.web.test": new Set(["results", "ok", "status", "reason"]),
};
function project(method: string, value: unknown): unknown { if (Array.isArray(value)) return value.map((entry) => project(method, entry)); if (!value || typeof value !== "object") return value; const allowed = fields[method]; if (!allowed) throw new Error(`Missing renderer result projection for ${method}.`); return Object.fromEntries(Object.entries(value).flatMap(([key, entry]) => allowed.has(key) ? [[key, project(method, entry)]] : [])); }
function denied(label: string) { return UClawErrorSchema.parse({ code: "FORBIDDEN", message: `${label}权限被拒绝，请在系统设置中授权后重试。`, retryable: false, recoveryActions: ["open-settings"], causeDetails: {} }); }
export function createOpenClawSystemVoiceService(options: OpenClawSystemVoiceOptions): SystemVoiceService {
  const memory = new Map<string, unknown>();
  const activeClientRuns = new Map<string, { sessionKey: string; runId: string }>();
  const talkSessions: SystemTalkSessionAuthority = options.talkSessions ?? { list: async () => [...memory.values()], record: async (id, value) => { memory.set(id, value); }, remove: async (id) => { memory.delete(id); }, clear: async () => { memory.clear(); } };
  const talkAuthority = async () => ({ scope: "owned-runtime", sessions: await talkSessions.list() });
  const permissions = () => options.permissions.get();
  const requirePermission = async (kind: keyof SystemVoicePermissions, label: string) => { const current = await permissions(); if (current[kind] === "denied" || current[kind] === "restricted") throw denied(label); if (current[kind] !== "granted") throw UClawErrorSchema.parse({ code: "AUTHORIZATION_REQUIRED", message: `${label}权限尚未授权，请在系统设置中授权后重试。`, retryable: false, recoveryActions: ["open-settings"], causeDetails: {} }); return current; };
  const unadvertisedCoreMethods = new Set(["push.web.vapidPublicKey", "push.web.subscribe", "push.web.unsubscribe", "push.web.test"]);
  const raw = async (method: string, params: unknown) => { if (!unadvertisedCoreMethods.has(method)) options.requireMethod(method); return options.request(method, params, Any); };
  const call = async (method: string, params: unknown) => project(method, await raw(method, params));
  const readback = async (method: string, params: unknown, readMethod: string, readParams: unknown = {}) => ({ mutation: await call(method, params), authority: await call(readMethod, readParams), permissions: await permissions() });
  return {
    getTalkRuntimeStatus: async () => ({ authority: await talkAuthority(), permissions: await permissions() }),
    createTalkSession: async (input) => { await requirePermission("microphone", "麦克风"); const mode = input.mode; const result = await call("talk.session.create", { ...(input.sessionKey ? { sessionKey: input.sessionKey } : {}), mode, transport: "gateway-relay", brain: mode === "transcription" ? "none" : "agent-consult" }) as Record<string, unknown>; if (typeof result.sessionId === "string") await talkSessions.record(result.sessionId, result); return { mutation: result, authority: await talkAuthority(), permissions: await permissions() }; },
    closeTalkSession: async (input) => { const mutation = await call("talk.session.close", input); await talkSessions.remove(input.sessionId); return { mutation, authority: await talkAuthority(), permissions: await permissions() }; },
    createTalkClient: async (input) => { await requirePermission("microphone", "麦克风"); const result = await raw("talk.client.create", input); const parsed = z.object({ provider: z.string().min(1), transport: z.literal("webrtc"), clientSecret: z.string().min(1), offerUrl: z.literal("https://api.openai.com/v1/realtime/calls").optional(), offerHeaders: z.record(z.string(), z.string()).optional(), model: z.string().min(1).optional(), voice: z.string().min(1).optional(), expiresAt: z.number().optional() }).strict().parse(result); return { clientBootstrap: { ...parsed, offerUrl: parsed.offerUrl ?? "https://api.openai.com/v1/realtime/calls", sessionKey: input.sessionKey ?? "main" }, permissions: await permissions() }; },
    runTalkClientTool: async (input) => { if (!options.waitForTalkRun) throw UClawErrorSchema.parse({ code: "UNCONFIGURED", message: "Talk 事件回桥未配置。", retryable: false, recoveryActions: ["open-diagnostics"], causeDetails: {} }); const accepted = await raw("talk.client.toolCall", input) as { runId?: unknown; idempotencyKey?: unknown }; const runId = typeof accepted.runId === "string" ? accepted.runId : accepted.idempotencyKey; if (typeof runId !== "string") throw new Error("Talk tool call did not return runId."); activeClientRuns.set(input.callId, { sessionKey: input.sessionKey, runId }); try { return await options.waitForTalkRun(runId); } finally { activeClientRuns.delete(input.callId); } },
    abortTalkClientTool: async (input) => { const active = activeClientRuns.get(input.callId); if (!active) return; if (!options.abortTalkRun) throw UClawErrorSchema.parse({ code: "UNCONFIGURED", message: "Talk 中止回桥未配置。", retryable: false, recoveryActions: ["open-diagnostics"], causeDetails: {} }); await options.abortTalkRun(active.sessionKey, active.runId); activeClientRuns.delete(input.callId); },
    steerTalkClient: (input) => call("talk.client.steer", input),
    clearTalkSessions: () => talkSessions.clear(),
    getTtsStatus: async () => ({ authority: await call("tts.status", {}), permissions: await permissions() }), listTtsProviders: async () => ({ authority: await call("tts.providers", {}), permissions: await permissions() }), setTtsProvider: (input) => readback("tts.setProvider", input, "tts.status"), listTtsPersonas: async () => ({ authority: await call("tts.personas", {}), permissions: await permissions() }), setTtsPersona: (input) => readback("tts.setPersona", input, "tts.status"), speak: async (input) => {
      if (!options.audioOutput) throw UClawErrorSchema.parse({ code: "UNCONFIGURED", message: "TTS 音频输出未配置。", retryable: false, recoveryActions: ["open-settings"], causeDetails: {} });
      const result = await raw("tts.speak", input) as { audioBase64?: unknown; mimeType?: unknown };
      if (typeof result.audioBase64 !== "string" || result.audioBase64.length === 0) throw UClawErrorSchema.parse({ code: "PROTOCOL_MAPPING_FAILED", message: "TTS 未返回音频。", retryable: false, recoveryActions: ["open-diagnostics"], causeDetails: {} });
      await options.audioOutput.play({ audioBase64: result.audioBase64, ...(typeof result.mimeType === "string" ? { mimeType: result.mimeType } : {}) });
      return { mutation: project("tts.speak", result), authority: await call("tts.status", {}), permissions: await permissions() };
    },
    getVoiceWake: async () => ({ authority: await call("voicewake.get", {}), permissions: await permissions() }), setVoiceWake: async (input) => { await requirePermission("microphone", "麦克风"); return readback("voicewake.set", input, "voicewake.get"); }, getVoiceWakeRouting: async () => ({ authority: await call("voicewake.routing.get", {}), permissions: await permissions() }), setVoiceWakeRouting: (input) => readback("voicewake.routing.set", input, "voicewake.routing.get"),
    getPushStatus: async () => ({ authority: { subscribed: Boolean(await options.pushSubscription?.get()) }, permissions: await permissions() }),
    subscribePush: async () => { await requirePermission("notifications", "通知"); if (!options.pushSubscription) throw UClawErrorSchema.parse({ code: "UNCONFIGURED", message: "系统 Push 订阅源未配置。", retryable: false, recoveryActions: ["open-settings"], causeDetails: {} }); const key = await raw("push.web.vapidPublicKey", {}) as { vapidPublicKey?: unknown }; if (typeof key.vapidPublicKey !== "string") throw new Error("Gateway did not return a VAPID public key."); const subscription = await options.pushSubscription.subscribe(key.vapidPublicKey); try { const mutation = await call("push.web.subscribe", subscription); return { mutation, authority: { subscribed: Boolean(await options.pushSubscription.get()) }, permissions: await permissions() }; } catch (error) { await options.pushSubscription.unsubscribe(); throw error; } },
    unsubscribePush: async () => { if (!options.pushSubscription) throw UClawErrorSchema.parse({ code: "UNCONFIGURED", message: "系统 Push 订阅源未配置。", retryable: false, recoveryActions: ["open-settings"], causeDetails: {} }); const subscription = await options.pushSubscription.get(); const mutation = subscription ? await call("push.web.unsubscribe", { endpoint: subscription.endpoint }) : { removed: false }; await options.pushSubscription.unsubscribe(); return { mutation, authority: { subscribed: Boolean(await options.pushSubscription.get()) }, permissions: await permissions() }; },
    testPush: async () => {
      await requirePermission("notifications", "通知");
      const mutation = await call("push.web.test", {}) as { results?: Array<{ ok?: boolean }> };
      if (!mutation.results?.some((result) => result.ok === true)) throw UClawErrorSchema.parse({ code: "OPERATION_FAILED", message: "Push 测试通知投递失败。", retryable: true, recoveryActions: ["retry", "open-diagnostics"], causeDetails: {} });
      return { mutation, authority: { subscribed: Boolean(await options.pushSubscription?.get()) }, permissions: await permissions() };
    },
  };
}
