import { Bell, Headphones, Mic, Radio, RefreshCw, Volume2, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { SystemVoiceIpcRequest, SystemVoiceIpcResponse } from "@uclaw/shared/dist/system-voice.js";
import { startTalkClientTransport, type TalkClientTransport } from "./talk-client-transport.js";
type Bridge = { invoke(request: SystemVoiceIpcRequest): Promise<SystemVoiceIpcResponse> }; type Row = Record<string, unknown>; type View = "talk" | "tts" | "wake" | "push";
const rows = (value: unknown, key: string): Row[] => Array.isArray((value as Row | undefined)?.[key]) ? (value as Row)[key] as Row[] : []; const text = (value: unknown) => typeof value === "string" ? value : ""; const authority = (value: unknown) => ((value as Row | undefined)?.authority ?? value) as Row;
export function AdvancedVoiceSettings({ bridge, startTalkClient = startTalkClientTransport }: { bridge?: Bridge; startTalkClient?: typeof startTalkClientTransport }) {
  const sequence = useRef(0); const talkClient = useRef<TalkClientTransport | null>(null); const [talkClientActive, setTalkClientActive] = useState(false); const [view, setView] = useState<View>("talk"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const [talk, setTalk] = useState<Row>({}); const [tts, setTts] = useState<Row>({}); const [providers, setProviders] = useState<Row[]>([]); const [personas, setPersonas] = useState<Row[]>([]); const [speech, setSpeech] = useState(""); const [triggers, setTriggers] = useState<string[]>([]); const [triggerInput, setTriggerInput] = useState("openclaw"); const [routing, setRouting] = useState<Row>({}); const [agentId, setAgentId] = useState("main"); const [push, setPush] = useState<Row>({});
  const call = useCallback(async (method: SystemVoiceIpcRequest["method"], params: Row) => { if (!bridge) throw new Error("语音与通知 RPC 未配置"); const response = await bridge.invoke({ method, requestId: `system-voice-${++sequence.current}`, params } as SystemVoiceIpcRequest); if (!response.ok) throw new Error(`${response.error.code}: ${response.error.message}`); return response.result; }, [bridge]);
  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(undefined); try { await operation(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const refresh = useCallback(async (target: View) => {
    if (target === "talk") setTalk(authority(await call("talk.runtime.status", {})));
    if (target === "tts") { const [status, providerResult, personaResult] = await Promise.all([call("tts.status", {}), call("tts.providers", {}), call("tts.personas", {})]); setTts(authority(status)); setProviders(rows(authority(providerResult), "providers")); setPersonas(rows(authority(personaResult), "personas")); }
    if (target === "wake") { const [wakeResult, routingResult] = await Promise.all([call("voicewake.get", {}), call("voicewake.routing.get", {})]); const wake = authority(wakeResult); setTriggers(Array.isArray(wake.triggers) ? wake.triggers.map(text).filter(Boolean) : []); setRouting(authority(routingResult)); }
    if (target === "push") setPush(authority(await call("push.web.status", {})));
  }, [call]);
  useEffect(() => { if (bridge) void run(() => refresh(view)); }, [bridge, refresh, view]); useEffect(() => () => { talkClient.current?.stop(); talkClient.current = null; setSpeech(""); setError(undefined); }, []);
  const mutate = (method: SystemVoiceIpcRequest["method"], params: Row) => run(async () => { await call(method, params); await refresh(view); });
  if (!bridge) return <section aria-label="语音与通知"><div className="empty-panel"><Mic /><strong>语音与通知 RPC 未配置</strong></div></section>;
  const talkSessions = rows(talk, "sessions"); const config = (routing.config ?? {}) as Row;
  return <section className="system-node-manager" aria-label="语音与通知" aria-busy={busy}><header className="data-toolbar"><strong>Talk、TTS、Voice Wake 与 Push</strong><button type="button" aria-label="刷新语音与通知" disabled={busy} onClick={() => void run(() => refresh(view))}><RefreshCw /></button></header><div role="tablist" className="system-node-tabs"><button role="tab" aria-selected={view === "talk"} onClick={() => setView("talk")}><Headphones />Talk</button><button role="tab" aria-selected={view === "tts"} onClick={() => setView("tts")}><Volume2 />TTS</button><button role="tab" aria-selected={view === "wake"} onClick={() => setView("wake")}><Radio />Voice Wake</button><button role="tab" aria-selected={view === "push"} onClick={() => setView("push")}><Bell />Push</button></div>{error ? <div role="alert" className="data-state"><strong>操作失败</strong><small>{error}</small></div> : null}<div className="system-node-content">
    {view === "talk" ? <div className="system-node-list"><button aria-label="创建 Gateway Talk 会话" onClick={() => void mutate("talk.session.create", { mode: "realtime" })}><Mic />Gateway 会话</button><button aria-label={talkClientActive ? "停止客户端 Talk 会话" : "创建客户端 Talk 会话"} onClick={() => { if (talkClient.current) { talkClient.current.stop(); talkClient.current = null; setTalkClientActive(false); return; } void run(async () => { const result = await call("talk.client.create", {}); if (!result || typeof result !== "object" || !("clientBootstrap" in result)) throw new Error("PROTOCOL_MAPPING_FAILED: Talk 客户端未返回连接信息"); const transport = await startTalkClient(result.clientBootstrap as never, undefined, { consult: (input) => call("talk.client.toolCall", input), abort: (input) => call("talk.client.abort", input).then(() => undefined), steer: (input) => call("talk.client.steer", input) }); talkClient.current = transport; setTalkClientActive(true); }); }}><Headphones />{talkClientActive ? "停止客户端" : "客户端会话"}</button>{talkSessions.map((item) => <article key={text(item.sessionId)}><span><strong>{text(item.sessionId)}</strong><small>{text(item.mode)} · {text(item.transport)}</small></span><button aria-label={`关闭 Talk 会话 ${text(item.sessionId)}`} onClick={() => void mutate("talk.session.close", { sessionId: text(item.sessionId) })}><X /></button></article>)}</div> : null}
    {view === "tts" ? <div className="system-node-list"><p>{tts.enabled ? `已启用 · ${text(tts.provider)} · ${text(tts.persona)}` : "TTS 未启用"}</p><select aria-label="TTS Provider" value={text(tts.provider)} onChange={(event) => void mutate("tts.setProvider", { provider: event.target.value })}>{providers.map((item) => <option key={text(item.id)} value={text(item.id)}>{text(item.name) || text(item.id)}</option>)}</select><select aria-label="TTS Persona" value={text(tts.persona)} onChange={(event) => void mutate("tts.setPersona", { persona: event.target.value || null })}><option value="">默认</option>{personas.map((item) => <option key={text(item.id)} value={text(item.id)}>{text(item.label) || text(item.id)}</option>)}</select><textarea aria-label="朗读文本" value={speech} onChange={(event) => setSpeech(event.target.value)} /><button aria-label="朗读" disabled={!speech.trim()} onClick={() => void mutate("tts.speak", { text: speech.trim() })}><Volume2 />朗读</button></div> : null}
    {view === "wake" ? <div className="system-node-list"><div className="system-node-create"><input aria-label="Voice Wake 触发词" value={triggerInput} onChange={(event) => setTriggerInput(event.target.value)} /><button aria-label="保存 Voice Wake 触发词" onClick={() => void mutate("voicewake.set", { triggers: triggerInput.split(",").map((item) => item.trim()).filter(Boolean) })}>保存</button></div>{triggers.map((item) => <article key={item}><strong>{item}</strong></article>)}<input aria-label="Voice Wake Agent" value={agentId} onChange={(event) => setAgentId(event.target.value)} /><button aria-label="保存 Voice Wake 路由" onClick={() => void mutate("voicewake.routing.set", { config: { version: 1, defaultTarget: { agentId }, routes: Array.isArray(config.routes) ? config.routes : [] } })}>保存路由</button></div> : null}
    {view === "push" ? <div className="system-node-list"><p>{push.subscribed ? "已订阅" : "未订阅"}</p><button aria-label="订阅 Push" onClick={() => void mutate("push.web.subscribe", {})}><Bell />订阅</button><button aria-label="测试 Push" disabled={!push.subscribed} onClick={() => void mutate("push.web.test", {})}>测试</button><button aria-label="取消 Push" disabled={!push.subscribed} onClick={() => void mutate("push.web.unsubscribe", {})}><X /></button></div> : null}
  </div></section>;
}
